### ISSUE TITLE
Vue.js Support?

### ISSUE THREAD

**Issue by loktarjugg** [Rovak/InlineAttachment#81]
Would you plan to support vue.js?  @Rovak

**Comment by Rovak** [comment]
vue.js already supports the use of plugins like jQuery. I guess you are looking for a vue.js directive?

In that case you could make a vue.js directive using the following code:

```
Vue.directive('inline-attachment', function (el, binding) {
  inlineAttachment.editors.input.attachToInput(el);
})
```

then use it like this:

```
<textarea inline-attachment></textarea>
```

Note that i haven't this code myself.

**Comment by loktarjugg** [comment]
I use it like that 
![image](https://cloud.githubusercontent.com/assets/3970144/23119592/d462591a-f793-11e6-9adf-fec85c96edc8.png)

When i paste a image , browser throw the bug :
![image](https://cloud.githubusercontent.com/assets/3970144/23119664/19c1a18c-f794-11e6-85b3-07eea45c4ece.png)

**Comment by loktarjugg** [comment]
I found the problem, because i used simplemde 

I refer to this link [issues](https://github.com/NextStepWebs/simplemde-markdown-editor/issues/328)

![image](https://cloud.githubusercontent.com/assets/3970144/23148740/735bf92a-f822-11e6-8998-5c535581d408.png)

and it works !

Thanks

**Comment by ashvin-php** [comment]
@loktarjugg I am new to vuejs. Can you please guide me how you put this inline attachment as vue directive. I am facing similar issue to integrate this inline attachment with vue-simplemde v1.0.4

Thanks.
